# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [5]:
import numpy as np
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [7]:
import numpy as np
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [9]:
np.full(100, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [15]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [16]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 6. Создать вектор со значениями от 10 до 100

In [19]:
from random import randint 
vector = [randint(10,100) for x in range(10)]
print(vector)

[89, 85, 56, 13, 50, 52, 48, 82, 45, 41]


#### 7. Развернуть вектор (первый становится последним)

In [20]:
vector = [1, 2, 3, 4, 5]
var = vector[0]
vector[0] = vector[len(vector)-1]
vector[len(vector)-1] = var
print(vector)

[5, 2, 3, 4, 1]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [21]:
matrix = np.arange(16).reshape(4,4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [27]:
arr = [1, 2, 3, 4, 5]
arr2 = []
for i in range(len(arr)): 
    k = arr[i]
    arr2.append(k)
    if (k < 5):
        arr2 += [0,0,0]

print(arr2)

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


#### 10. Создать 3x3 единичную матрицу

In [31]:
import numpy as np
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Создать массив 3x3x3 со случайными значениями

In [33]:
import numpy as np
arr= np.random.random((1,3,3))
print(arr)

[[[0.37464383 0.05927792 0.6174685 ]
  [0.62292812 0.89837612 0.42747936]
  [0.19165547 0.90755789 0.08708819]]]


#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [34]:
import numpy as np
arr = np.random.random((10,10))
min = arr.min()
max = arr.max()
print(min, max)

0.009884192084469334 0.9872265018606855


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [35]:
from random import randint 


def mySum(arrlist):
    Sum = 0
    for i in arrlist:
        Sum = Sum + i
    return Sum


arr = [randint(10,100) for x in range(30)]
value = mySum(arr)/30

print(value)


47.96666666666667


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [36]:
arr = []
n = int(input())
if n<2:
    print(1)
else:
    arr.append(1)
    for i in range(1,n-1,1):
        arr.append(0)
    arr.append(1)
print(arr)

3
[1, 0, 1]


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [38]:
arr = np.diag([1,2,2,4],k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 4 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [40]:
arr = np.zeros((8,8), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [41]:
import numpy as np

print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [42]:
chess = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(chess)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [43]:
import numpy as np

arr = np.dot(np.ones((5,3)), np.ones((3,2)))
print(arr)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [46]:
n = int(input())
a = [randint(0,10) for x in range(n)]
for i in range(n):
    if (a[i]>2) and (a[i]<9):
        a[i]=-a[i]
        
print(a)

5
[1, -5, 9, 2, 9]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [47]:
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 24. Есть генератор, сделать с его помощью массив

In [49]:
import numpy as np

def generate():
    for x in range(10):
        yield x
arr = np.fromiter(generate(),dtype = float,count=-1)
print(arr)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [50]:
import numpy as np

arr = np.linspace(0,1,12)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26. Отсортировать вектор

In [52]:
from random import randint 

vector = [randint(1,100) for x in range(15)]
vector.sort()
print(vector)


[7, 11, 14, 31, 37, 42, 47, 51, 53, 57, 63, 71, 74, 78, 92]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [53]:
import numpy as np

arr_1 = np.random.randint(0,2,5)
arr_2 = np.random.randint(0,2,5)
equal = np.allclose(arr_1, arr_2)
print(equal)

False


#### 28. Сделать массив неизменяемым

In [54]:
arr = np.ones(10)
arr.flags.writeable = False

#### 29. Найти n наибольших значений в массиве

In [55]:
from random import randint 

arr = [randint(1,100) for x in range(20)]
arr.sort()
n = int(input())
for i in range(len(arr)-n,len(arr),1):
    print(arr[i])

6
62
72
87
96
100
100


#### 30. Заменить максимальный элемент на ноль

In [57]:
max = []
n =int(input())
arr = [randint(0,1000) for x in range(n)]
max= arr[0]
for i in range(n):
  if arr[i]>max:
    max = arr[i]
    j = i
arr[j] = 0

print(arr)

6
[415, 385, 125, 130, 0, 401]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [58]:
arr = np.tile(np.array([[0,1],[1,0]]), (5,5))
print(arr)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [61]:
a = (1,2)
b = (9,5)
c = 1 / np.subtract.outer(a, b)
print(c)

[[-0.125      -0.25      ]
 [-0.14285714 -0.33333333]]


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [59]:
import numpy as np

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 34. Напечатать все значения в массиве

In [63]:
from random import randint 
arr = [randint(1,100) for x in range(10)]
for i in range(10):
    print(arr[i])

3
10
73
83
80
10
26
3
88
32


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [65]:
from random import randint 

arr = [randint(0,100) for x in range(10)]
n = int(input())
k = arr[0]
for i in range(10):
    if abs(arr[i]-n) < k:
        min = arr[i]
        k = abs(arr[i]-n)
print(min)

6
27


#### 36. Преобразовать массив из float в int

In [66]:
arr = np.arange(10, dtype=np.int32)
arrint = arr.astype(np.float32, copy=False)

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [67]:
import numpy as np

arr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(arr):
    print(index, value)
for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. Случайно расположить p элементов в 2D массив

In [68]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)

#### 39. Отнять среднее из каждой строки в матрице

In [69]:
X = np.random.rand(1, 10)
Y = X - X.mean(axis = 1, keepdims=True)

#### 40. Отсортировать матрицу по n-ому столбцу

In [70]:
arr = np.random.randint(1,10,(5,5))
n = int(input())
print(arr)
print(arr[arr[:,n].argsort()])

2
[[4 2 5 6 7]
 [9 1 2 1 1]
 [6 2 5 1 9]
 [2 2 5 2 9]
 [2 5 3 1 1]]
[[9 1 2 1 1]
 [2 5 3 1 1]
 [4 2 5 6 7]
 [6 2 5 1 9]
 [2 2 5 2 9]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [71]:
arr = np.random.randint(1,3,(3,10))
print((~arr.any(axis=0)).any())

False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [72]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 2. 6. 4. 2. 2. 3. 2. 3.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [73]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [74]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[58 51 54 56]
 [70 70 43 62]
 [65 36 62 60]]
